# -*- coding: utf-8 -*-
"""Breast Cancer Binary Classification (LDA Section).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mz4v9LQO3cS1dMt07SZ05QU8Hhgq0cdd
"""

# imports
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import (
    LinearDiscriminantAnalysis,
    QuadraticDiscriminantAnalysis,
)

# import dataset from kaggle
!wget --no-check-certificate "https://www.kaggle.com/api/v1/datasets/download/yasserh/breast-cancer-dataset" -O dataset.zip
!unzip -q dataset.zip
df = pd.read_csv("breast-cancer.csv")

# format data for use
n = 569
d = 30

X = df[["radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean",
        "concave points_mean", "symmetry_mean", "fractal_dimension_mean", "radius_se", "texture_se", "perimeter_se", "area_se",
        "smoothness_se", "compactness_se", "concavity_se", "concave points_se", "symmetry_se", "fractal_dimension_se",
        "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst", "compactness_worst",
        "concavity_worst", "concave points_worst", "symmetry_worst", "fractal_dimension_worst"]]
Y = df['diagnosis'].map({'B': 0, 'M': 1})
X = X.to_numpy()
Y = Y.to_numpy()

# split data into training and testing, using random seed
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, train_size=.5, test_size=.5,
    random_state=103
)

# create lda model and fit
lda = LinearDiscriminantAnalysis(solver="svd", store_covariance=True)
lda.fit(X_train, y_train)

# calculate lda testing score and display
scoreLDA = lda.score(X_test, y_test)
print('LDA Testing score was ' + str(scoreLDA) + '\n')

# create qda model and fit
qda = QuadraticDiscriminantAnalysis(reg_param=0.1, store_covariance=True)
qda.fit(X_train, y_train)

# calculate qda testing score and display
scoreQDA = qda.score(X_test, y_test)
print('QDA Testing score was ' + str(scoreQDA) + '\n')