# -*- coding: utf-8 -*-
"""Breast Cancer Binary Classification (Logistic Regression Section).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgXvDCzD1th4rMw7Ta8IWXQellDAEvq4
"""

# imports
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd

# import dataset from kaggle
!wget --no-check-certificate "https://www.kaggle.com/api/v1/datasets/download/yasserh/breast-cancer-dataset" -O dataset.zip
!unzip -q dataset.zip
df = pd.read_csv("breast-cancer.csv")

# format data for use
n = 569
d = 30

X = df[["radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean",
        "concave points_mean", "symmetry_mean", "fractal_dimension_mean", "radius_se", "texture_se", "perimeter_se", "area_se",
        "smoothness_se", "compactness_se", "concavity_se", "concave points_se", "symmetry_se", "fractal_dimension_se",
        "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst", "compactness_worst",
        "concavity_worst", "concave points_worst", "symmetry_worst", "fractal_dimension_worst"]]
Y = df['diagnosis'].map({'B': 0, 'M': 1})
X = X.to_numpy()
Y = Y.to_numpy()

# split data into training and testing, using random seed
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, train_size=.5, test_size=.5,
    random_state=103
)
num_training_data = X_train.shape[0]

# hyperparameter values to test
test_hyperparam = [.0001,.01,.1,1.,10.,100.,1000.,10000., 1000000.]

# track testing scores for each hyperparameter value
test_scores = []

# Repeat the Logistic Regression function, fitting, and scoring for each hyperparameter value
for tmp in test_hyperparam:
    inv_reg_coeff = tmp / num_training_data

    # C is Inverse of regularization strength; smaller values specify stronger regularization.
    clf = LogisticRegression(C=inv_reg_coeff,
                             penalty="l2",
                             solver="saga",
                             tol=0.1)
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    test_scores.append(score)
    train_score = clf.score(X_train, y_train)

# display table with testing scores for each hyperparameter value
print("Logistic Regression with L2 Penalty")
testing_table = {
    "Hyperparameter": test_hyperparam,
    "Testing Score": test_scores
}
df = pd.DataFrame(testing_table)
print(df)

# plot testing score vs hyperparameter value
plt.plot(test_hyperparam, test_scores)
plt.ylim(0.35, 1)
plt.xscale("log")

# labels and title of plot
plt.xlabel("Hyperparameter Value")
plt.ylabel("Testing Score")
plt.title("Testing Score vs Hyperparameter Value for Logistic Regression with L2 Penalty")

# display plot
print('\n')
plt.show()

# hyperparameter values to test
test_hyperparam = [.0001,.01,.1,1.,10.,100.,1000.,10000., 1000000.]

# track testing scores for each hyperparameter value
test_scores = []

# Repeat the Logistic Regression function, fitting, and scoring for each hyperparameter value
for tmp in test_hyperparam:
    inv_reg_coeff = tmp / num_training_data

    # C is Inverse of regularization strength; smaller values specify stronger regularization.
    clf = LogisticRegression(C=inv_reg_coeff,
                             penalty="l1",
                             solver="saga",
                             tol=0.1)
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    test_scores.append(score)
    train_score = clf.score(X_train, y_train)

# display table with testing scores for each hyperparameter value
print("Logistic Regression with L1 Penalty")
testing_table = {
    "Hyperparameter": test_hyperparam,
    "Testing Score": test_scores
}
df = pd.DataFrame(testing_table)
print(df)

# plot testing score vs hyperparameter value
plt.plot(test_hyperparam, test_scores)
plt.ylim(0.35, 1)
plt.xscale("log")

# labels and title of plot
plt.xlabel("Hyperparameter Value")
plt.ylabel("Testing Score")
plt.title("Testing Score vs Hyperparameter Value for Logistic Regression with L1 Penalty")

# display plot
print('\n')
plt.show()