# -*- coding: utf-8 -*-
"""Breast Cancer Binary Classification (SVM Section).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrhQpwJEsl8cv6DyREIDfAr3_zdeeJ3g
"""

# imports
import numpy as np
import sklearn as sk
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import svm
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# import dataset from kaggle
!wget --no-check-certificate "https://www.kaggle.com/api/v1/datasets/download/yasserh/breast-cancer-dataset" -O dataset.zip
!unzip -q dataset.zip
df = pd.read_csv("breast-cancer.csv")

# format data for use
n = 569
d = 30

X = df[["radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean",
        "concave points_mean", "symmetry_mean", "fractal_dimension_mean", "radius_se", "texture_se", "perimeter_se", "area_se",
        "smoothness_se", "compactness_se", "concavity_se", "concave points_se", "symmetry_se", "fractal_dimension_se",
        "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst", "compactness_worst",
        "concavity_worst", "concave points_worst", "symmetry_worst", "fractal_dimension_worst"]]
Y = df['diagnosis'].map({'B': 0, 'M': 1})
X = X.to_numpy()
Y = Y.to_numpy()

# split data into training and testing, using random seed
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, train_size=.5, test_size=.5,
    random_state=103
)
num_training_data = X_train.shape[0]

# hyperparameter values to test
test_hyperparam = [.0001,.01,.1,1.,10.,100.,1000.,10000., 1000000.]

# track testing scores for each hyperparameter value with RBF kernel
RBF_test_scores = []

# Repeat the SVM function with RBF kernel, fitting and scoring for each hyperparameter value
for tmp in test_hyperparam:
    inv_reg_coeff = tmp/num_training_data

    #C is Inverse of regularization strength; smaller values specify stronger regularization
    clf = svm.SVC(C=inv_reg_coeff)
    clf.fit(X_train, y_train)

    score = clf.score(X_test, y_test)
    RBF_test_scores.append(score)

# display table with testing scores for each hyperparameter value
print("SVM with RBF kernel")
testing_table = {
    "Hyperparameter": test_hyperparam,
    "Testing Score": RBF_test_scores
}
df = pd.DataFrame(testing_table)
print(df)

# plot testing score vs hyperparameter value
plt.plot(test_hyperparam, RBF_test_scores)
plt.ylim(0.35, 1)
plt.xscale("log")

# labels and title
plt.xlabel("Hyperparameter Value")
plt.ylabel("Testing Score")
plt.title("Testing Score vs Hyperparameter Value for RBF SVM")

# display plot
print('\n')
plt.show()

# track testing scores for each hyperparameter value with linear kernel
linear_test_scores = []

# Repeat the SVM function with linear kernel, fitting and scoring for each hyperparameter value
for tmp in test_hyperparam:
    inv_reg_coeff = tmp/num_training_data

    #C is Inverse of regularization strength; smaller values specify stronger regularization.
    clf = svm.SVC(C=inv_reg_coeff, kernel = 'linear')
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    linear_test_scores.append(score)

# display table with testing scores for each hyperparameter value
print('\n' + 'SVM with Linear kernel:')
testing_table = {
    "Hyperparameter": test_hyperparam,
    "Testing Score": linear_test_scores
}
df = pd.DataFrame(testing_table)
print(df)

# plot testing score vs hyperparameter value
plt.plot(test_hyperparam, linear_test_scores)
plt.ylim(0.35, 1)
plt.xscale("log")

# labels and title
plt.xlabel("Hyperparameter Value")
plt.ylabel("Testing Score")
plt.title("Testing Score vs Hyperparameter Value for Linear SVM")

# display plot
print('\n')
plt.show()

# model with highest testing score
clf = svm.SVC(C=100/num_training_data, kernel = 'linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# find true/false positives/negatives
true_class = np.where(y_test == y_pred)[0]
true_pos = np.where(y_test[true_class] == 1)[0]
true_neg = np.where(y_test[true_class] == 0)[0]
false_pos = np.where(y_pred > y_test)[0]
false_neg = np.where(y_pred < y_test)[0]

# calculate sensitivity and specificity
num_true_pos = len(true_pos)
num_true_neg = len(true_neg)
num_false_pos = len(false_pos)
num_false_neg = len(false_neg)
print('Number of False Positives: ',num_false_pos)
print('Number of False Negatives: ',num_false_neg)
print('Sensitivity = ', num_true_pos/(num_true_pos + num_false_neg))
print('Specificity = ', num_true_neg/(num_true_neg + num_false_pos))
print('\n')

# modify predictions to display false classifications
y_pred[false_pos] = 2
y_pred[false_neg] = 3

# print bar chart of features and their respective coefficients in the model
features = ["Radius Mean", "Texture Mean", "Perimeter Mean", "Area Mean", "Smoothness Mean", "Compactness Mean", "Concavity Mean",
        "Concave Points Mean", "Symmetry Mean", "Fractal Dimension Mean", "Radius SE", "Texture SE", "Perimeter SE", "Area SE",
        "Smoothness SE", "Compactness SE", "Concavity SE", "Concave Points SE", "Symmetry SE", "Fractal Dimension SE", "Radius Worst",
        "Texture Worst", "Perimeter Worst", "Area Worst", "Smoothness Worst", "Compactness Worst", "Concavity Worst",
        "Concave Points Worst", "Symmetry Worst", "Fractal Dimension Worst"]
plt.barh(features, clf.coef_[0])
plt.title("Feature Coefficients of Best Model")
plt.show()

# reduce testing data using PCA
X2 = PCA(n_components=2).fit_transform(X_test)

# create scatter plot of predicted values, with points displayed along the PCA dimensions
colors = ['blue', 'orange','red','purple']
plt.scatter(X2[:,0], X2[:,1], c=[colors[i] for i in y_pred], alpha=0.7)
# title and legend
plt.title("PCA Approximation of Best Model")
blue_patch = mpatches.Patch(color='blue', label='Benign')
orange_patch = mpatches.Patch(color='orange', label='Malignant')
red_patch = mpatches.Patch(color='red', label='False Malignant')
purple_patch = mpatches.Patch(color='purple', label='False Benign')
plt.legend(handles=[blue_patch, orange_patch, purple_patch, red_patch])

# display plot
plt.show()



# identify two highest weighted features by absolute coefficient
coefs = clf.coef_[0]
sorted_idx = np.argsort(np.abs(coefs))[::-1]
top2 = sorted_idx[:2]

# reduce testing data to the top two features
X2 = X_test[:, top2]

# plot predicted values, with points displayed by the top two features
colors = ['blue', 'orange','red','purple']
scatter = plt.scatter(X2[:,0], X2[:,1], c=[colors[i] for i in y_pred], alpha=0.7)

# title, labels, and legend
plt.title("Top 2 Feature Approximation of Best Model")
plt.xlabel(features[top2[0]])
plt.ylabel(features[top2[1]])
blue_patch = mpatches.Patch(color='blue', label='Benign')
orange_patch = mpatches.Patch(color='orange', label='Malignant')
red_patch = mpatches.Patch(color='red', label='False Malignant')
purple_patch = mpatches.Patch(color='purple', label='False Benign')
plt.legend(handles=[blue_patch, orange_patch, purple_patch, red_patch])

# display plot
plt.show()